// Code generated by MockGen. DO NOT EDIT.
// Source: channel.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	usecase "github.com/girakdev/girack-backend/application/usecase"
	gomock "github.com/golang/mock/gomock"
)

// MockChannelUsecase is a mock of ChannelUsecase interface.
type MockChannelUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockChannelUsecaseMockRecorder
}

// MockChannelUsecaseMockRecorder is the mock recorder for MockChannelUsecase.
type MockChannelUsecaseMockRecorder struct {
	mock *MockChannelUsecase
}

// NewMockChannelUsecase creates a new mock instance.
func NewMockChannelUsecase(ctrl *gomock.Controller) *MockChannelUsecase {
	mock := &MockChannelUsecase{ctrl: ctrl}
	mock.recorder = &MockChannelUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelUsecase) EXPECT() *MockChannelUsecaseMockRecorder {
	return m.recorder
}

// GetChannelList mocks base method.
func (m *MockChannelUsecase) GetChannelList(ctx context.Context, input *usecase.GetChannelListInput) (*usecase.GetChannelListOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelList", ctx, input)
	ret0, _ := ret[0].(*usecase.GetChannelListOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelList indicates an expected call of GetChannelList.
func (mr *MockChannelUsecaseMockRecorder) GetChannelList(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelList", reflect.TypeOf((*MockChannelUsecase)(nil).GetChannelList), ctx, input)
}

// MockChannelLister is a mock of ChannelLister interface.
type MockChannelLister struct {
	ctrl     *gomock.Controller
	recorder *MockChannelListerMockRecorder
}

// MockChannelListerMockRecorder is the mock recorder for MockChannelLister.
type MockChannelListerMockRecorder struct {
	mock *MockChannelLister
}

// NewMockChannelLister creates a new mock instance.
func NewMockChannelLister(ctrl *gomock.Controller) *MockChannelLister {
	mock := &MockChannelLister{ctrl: ctrl}
	mock.recorder = &MockChannelListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelLister) EXPECT() *MockChannelListerMockRecorder {
	return m.recorder
}

// GetChannelList mocks base method.
func (m *MockChannelLister) GetChannelList(ctx context.Context, input *usecase.GetChannelListInput) (*usecase.GetChannelListOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelList", ctx, input)
	ret0, _ := ret[0].(*usecase.GetChannelListOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelList indicates an expected call of GetChannelList.
func (mr *MockChannelListerMockRecorder) GetChannelList(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelList", reflect.TypeOf((*MockChannelLister)(nil).GetChannelList), ctx, input)
}
