version: '3'

services:
  http-server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    container_name: http-server
    volumes:
      - .:/go/src/app/
    command:
      sh -c "go run main.go"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=girack
