version: '3'

services:
  girack-server:
    container_name: grack-server
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"
    command: /bin/sh -c "go run main.go"

  postgres:
    container_name: girack_db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=girack_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=girack_db
    volumes:
      - /etc/localtime:/etc/localtime:ro
    user: root

