version: '3'

services:
  girack-server:
    container_name: grack-server
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/girack?sslmode=disable
    volumes:
      - ./app:/go/src/app

  postgres:
    #restart: always テストでは使わない
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
    user: root

