version: '3'

services:
  girack-server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    container_name: grack-server
    volumes:
      - ./app:/go/src/app
    command:
      sh -c "go run main.go"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=girak
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=girack
