version: '3'

services:
  girack-server:
    container_name: grack-server
    build:
      context: .

    ports:
      - "8080:8080"
    depends_on:
      - postgres

    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/girack?sslmode=disable

    volumes:
      - ./app:/go/src/app
    command:
      sh -c "go run main.go"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432
    user: root
