version: '3'

services:
  girack-server:
    container_name: girack-server
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - FTP_PROXY=$FTP_PROXY
      - ftp_proxy=$ftp_proxy
      - NO_PROXY=$NO_PROXY
      - no_proxy=$no_proxy

      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - "./app:/go/src/app"
    command: go run main.go

  postgres:
    container_name: girack_db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5432:5432

