version: '3'
services:
  girack:
    container_name: girack
    build:
      dockerfile: ./docker/go/DockerFile
    expose:
      - "8080"
    ports: 
      - 8080:8080
    env_file:
      - ./env.local
    volumes:
      - .:/app
    command: air -c ./.air.toml

  db:
    container_name: db 
    image: postgres:latest
    env_file:
      - ./env.local
    ports: 
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local