definitions:
  model.Channel:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  model.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /channels:
    get:
      consumes:
      - application/json
      description: List Channel
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Channel'
            type: array
      summary: List Channel
      tags:
      - channels
    post:
      consumes:
      - application/json
      description: Create Channel
      parameters:
      - description: チャンネル名
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Channel'
        "500":
          description: Internal Server Error
      summary: Create Channel
      tags:
      - channels
  /channels/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Channel
      parameters:
      - description: チャンネルID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete Channel
      tags:
      - channels
    get:
      consumes:
      - application/json
      description: Get Channel
      parameters:
      - description: チャンネルID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Channel'
      summary: Get Channel
      tags:
      - channels
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - example
  /users:
    delete:
      consumes:
      - application/json
      description: Delete User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Delete User
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get List User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: List User
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Create User
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Update User
      tags:
      - users
swagger: "2.0"
